### ISSUE TITLE
nr-distributor understanding

### ISSUE THREAD

**Issue by andybjackson** [simonyiszk/openwrt-rrm-nr-distributor#1]
Dear "kissadamfkut" and all,

Wanted to try to understand this script a little better. In my scenario of three WiFi Routers/Access Points in my house, fast roaming is important in order not to drop calls as my family and I move around.

The main Router / Access point is a xDSL modem router (BT Home Hub 5A as it happens). Then there are two satellites (Xiaomi Mi Gigabit 4a) working in dumb access points. In this scenario, rrm-nr-distirbutor is probably a little overkill as I could just script directly that the optimal neighbourhood list is configured. That said, I like the flexibility of anticipating that it might change and that wouldn't trigger the need for scripts to be updated.

So my questions then:
- Why is it necessary to advertise dropbear and its port via umdns? Couldn't each device only advertise the neighbourhood list contributions? Does each device use the dropbear details of the other? If so, how is login achieved? And how is what they have access to limited?
- Not all configs seem to get published all of the time. Initial testing was with just the 5GHz radios. Each device should have had the entries of the two others, but often one would be missing from the other two. Then I updated all three to the most recent snapshot and also activated 2.4G. Now the Home Hub has both the others' 2.4G entries but only one 5G, whereas the Xiaomi Mi G4a's have both 5G entries (each others' and the BTHH5a) but only one 2.4G entry (each others' and NOT the BTHH5a). What is the mechanism by which information is kept complete and current (i.e. what is the trigger for refreshing)?
- Where might one find how to decode/understand the neighbourhood report JSON?

**Comment by kissadamfkut** [comment]
Hello!

To turn off dropbear service report you need to edit /etc/init.d/dropbear , it is not related to this program
As the reports are distributed through multicast dns, this shows an umdns misconfig. At home I see a little delay when doing cold boot, but the list convergates to full early.
Are you asking about JSON ubus reports?

Adam

**Comment by andybjackson** [comment]
Thank you. The list didn't yet seem to converge for me, but I'll keep probing as to why. Yes I am keen to understand the part of the JSON that isn't the SSID or the MAC address. And the format of the message overall (JSON structure itself).

Thanks Adam!
