### ISSUE TITLE
Openwrt renamed hostapd.wlan* to hostapd.phy*.ap*

### ISSUE THREAD

**Issue by andybjackson** [simonyiszk/openwrt-rrm-nr-distributor#3]
Openwrt seems to have renamed `hostapd.wlan*` to `hostapd.phy*.ap0`. This is causing openwrt-rrm-nr-distributor to fail in the most recent snapshot.

**Comment by andybjackson** [comment]
@kissadamfkut Any chance of updating? My skills aren't quite there but I'll give it a bash if you don't.

**Comment by kissadamfkut** [comment]
I see you've opened a PR, will take a look at the weekend.

**Comment by andybjackson** [comment]
@kissadamfkut gentle reminder.

**Comment by kissadamfkut** [comment]
Approved on OPENWRT_RELEASE="OpenWrt 22.03.0 r19685-512e76967f"
