### ISSUE TITLE
Dependency on umdns 

### ISSUE THREAD

**Issue by andybjackson** [simonyiszk/openwrt-rrm-nr-distributor#9]
The switch to TXT record per neighbour seems to have created a dependency on a later version of umdns than is merged into OpenWRT Master by default (2023-01-16 vs 2021-05-13).

Do I just need to be patient for the 5 John Crispin authored mdnsd commits to make it from https://git.openwrt.org/?p=project/mdnsd.git into OpenWRT? How does this happen by the way?

Until then, rrm_nr is broken for me. @Fail-Safe or @kissadamfkut can you update please?

**Comment by Fail-Safe** [comment]
I'm working behind the scenes to see if we can get the umDNS Makefile updated to HEAD of that project. That would resolve this dependency issue.

Until then, are you able to review this post and see if it helps you get back to a workable state?

https://forum.openwrt.org/t/802-11k-neighbor-report-daemon/102984/11?u=_failsafe

**Comment by Fail-Safe** [comment]
I raised the PR to get this updated in the OpenWrt repo:
https://github.com/openwrt/openwrt/pull/12582

**Comment by andybjackson** [comment]
> I'm working behind the scenes to see if we can get the umDNS Makefile updated to HEAD of that project. That would resolve this dependency issue.
> 
> Until then, are you able to review this post and see if it helps you get back to a workable state?
> 
> https://forum.openwrt.org/t/802-11k-neighbor-report-daemon/102984/11?u=_failsafe

Yes. I had already gone back to this earlier version which still works. Very happy with the next steps you have now taken.

Will watch over the next day or two hopefully to see this through to resolution.

**Comment by Fail-Safe** [comment]
Sounds good. Glad you were able to get back into a working state in the interim.

FYI, don't be surprised if it takes a couple weeks still before the PR I introduced gets pulled into the OpenWrt master branch. It can take some time even from here.

**Comment by Fail-Safe** [comment]
@andybjackson This has been merged into snapshot per: https://github.com/openwrt/openwrt/commit/ce81896769412fdab838efcb4b79d1981e166372

**Comment by andybjackson** [comment]
umdns now updated & updated script now working for me.
